In [1]:
# %matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

import mglearn
import sklearn
from sklearn.decomposition import PCA
from sklearn.datasets import load_breast_cancer

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2.,1.,4.]])
print(M)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]


In [3]:
b = np.array([1.,3.,7.])
print(b)

[1. 3. 7.]


# Método de eliminación Gaussiana

1. Diagonalizar la matriz con unos en la diagonal
2. Hacer la sustiución hacia atrás $ x_{i} = \frac{b_{i} - \sum_{j = i+1}^{n} a_{ij}x_{j}}{a_{ii}} $